name: publish to dockerhub
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  publish-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code # 拉取代码
        uses: actions/checkout@v3
      - name: Login to Docker Hub # 登录到DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: into TestServer folder # 进入项目文件夹
        run: cd TestServer
      - name: Build and push # 构建并推送
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kentxxq/test-server:latest